### ISSUE TITLE
Not working with internal apps

### ISSUE THREAD

**Issue by abnersajr** [Fantomas42/django-livereload#12]
I have an contact app and isn't working with them.
I will show some prints with the code of my app.
![urls py](https://cloud.githubusercontent.com/assets/1998649/12748717/451924ca-c993-11e5-8ae1-3e7df23c6c4e.jpg)
![contato_app_views py](https://cloud.githubusercontent.com/assets/1998649/12748744/7582b5b8-c993-11e5-8497-6c943308d404.jpg)

when I access the URL livereload tab on console not detect that I went to the Contact view.

If necessary others information I would like to help you.

**Comment by Fantomas42** [comment]
Hello,
I'm sorry but I don't understand your issue...

django-livereload just send a reload signal when the development server is launched, and optionally inject the reload script into your page if you have activated the dedicated middleware. 

PS: I don't know what is the "livereload tab on console"...

**Comment by abnersajr** [comment]
I use a Cmder on Windows. I can use more than one tab, each tab is like 
one command prompt.
livereload tab is the tab with show live reload informations.

As you can see I use TemplateView.asView() to some routes.

To contact I use ContactView.asView()

He isn't injecting the livereload script on Contact view.
They not detect the change of page, when I access the contact page.

**Comment by Fantomas42** [comment]
And I suppose that you have registered the 'livereload.middleware.LiveReloadScript' middleware.

Does the script is injected on other pages ?

**Comment by abnersajr** [comment]
Yes, is injected on other pages. If you wan't I can provide you 
teamviewer access to my computer :)

**Comment by abnersajr** [comment]
I think the problem is when you try to acces other APP.

I have contact like an APP, on installed_apps: 'app.contact'
If I access "app" routes work.
If I try to access "app.<other_app>", I also have news like app.news

There is a problem.

**Comment by Fantomas42** [comment]
So the issue is coming from your URLconf...

It's not related to livereload itself no ?
