### ISSUE TITLE
Doesn't seem to work at all.

### ISSUE THREAD

**Issue by GeorgeTG** [Fantomas42/django-livereload#14]
When I have the middleware installed, when I try to run the server i get

> lib/python3.5/site-packages/django/core/handlers/base.py", line 82, in load_middleware
>     mw_instance = middleware(handler)
> TypeError: object() takes no parameters

When I remove the middleware and try to run with a custom `livereload-js`
I get:
> LiveReload exception: <urlopen error [Errno 111] Connection refused>

**Comment by Fantomas42** [comment]
Hello,

it's fixed in the latest release v1.7.

Regards

**Comment by fandrefh** [comment]
I've got the same error. Your version is 1.7.

**Comment by fandrefh** [comment]
I've got the same error. Version is 1.7.

**Comment by intrepidocabral** [comment]
same error here. Using version 1.7. Django version 1.8

**Comment by trsh** [comment]
Also getting this

**Comment by trsh** [comment]
@Fantomas42 please reopen!

**Comment by ARJOM** [comment]
Still with same error
