### ISSUE TITLE
Why should django local server and tinylr listen to the same port ?

### ISSUE THREAD

**Issue by konoufo** [Fantomas42/django-livereload#15]
The `runserver` command is making django listen to the same port as would the tinylr server. Why is that ? If i'm understanding everything right, i should be running my tinylr server (with node in my case) and then run django server "as usual" except the django server would regularly send notes to the tinylr server. So why does this app assign the tinylr listening port as default port for the django local server  when running `python manage.py runserver` ?

**Comment by Fantomas42** [comment]
Hello,

where do you see that the runserver will listen on the same port that livereload ?

I just checked the code, and I don't see this.

Regards

**Comment by konoufo** [comment]
~~~~
class Command(RunserverCommand):
    """
    Command for running the development server with LiveReload.
    """
    # Allow a settings option to set the default port
    default_port = getattr(settings, 'LIVERELOAD_PORT', '35729')
    # Allow a settings option to set the default host
    default_host = getattr(settings, 'LIVERELOAD_HOST', 'localhost')
~~~~
Here, those attributes make runserver listen on exactly the livereload port when everything is set to default or settings.py is used to set `LIVERELOAD_PORT` and `LIVERELOAD_HOST`.

**Comment by Fantomas42** [comment]
Yeah, so ?

These parameters are used in livereload_request method, not to make the runserver listen on these.

Regards

**Comment by konoufo** [comment]
yeah, but these parameters also happen to be used in the original runserver Command you are inheriting from. See the parent Command class here : [django.core.mangement.commands.runserver (github)](https://github.com/django/django/blob/master/django/core/management/commands/runserver.py)

**Comment by Fantomas42** [comment]
Can you indicate me the line, because I don't see where a parameter like livereload_port or livereload_host used somewhere in this code ?

**Comment by konoufo** [comment]
I think you're misunderstanding. You're setting `default_port` here:
```
    # Allow a settings option to set the default port
    default_port = getattr(settings, 'LIVERELOAD_PORT', '35729')
```
And this attribute `default_port` that you're setting is also used in the parent `Command` class' `handle` method to set the default port django local server listen to. Just look at line 79 : [djangp.core.management.commands.runserver (github) L79](https://github.com/django/django/blob/master/django/core/management/commands/runserver.py#L79)

**Comment by Fantomas42** [comment]
Okay these lines cause an issue

https://github.com/Fantomas42/django-livereload/blob/develop/livereload/management/commands/runserver.py#L25
https://github.com/Fantomas42/django-livereload/blob/develop/livereload/management/commands/runserver.py#L37

I will fix it asap.
