### ISSUE TITLE
No livereload script injected

### ISSUE THREAD

**Issue by F1LT3R** [Fantomas42/django-livereload#5]
Hi @Fantomas42, great idea to use livereload!

How are you launching tinylr from Gulp/Grunt?
Can you put an example in your README?

After following your steps, I can see that the livereload server is running at `http://127.0.0.1:35729/`

```json
{
"tinylr": "Welcome",
"version": "0.0.5"
}
```

But I get no livereload script injection. I would have expected your plugin took care of this when serving a file via Django's `static` dir?

I am attempting to launch livereload using `grunt-contrib-watch`.

**Comment by Fantomas42** [comment]
I will write a middleware for injecting the script, it's a good idea.

About the config to launch the livereload server, I think it's out of the scope. Many examples are available over internet, and they are no definitive way to launch the server.

**Comment by F1LT3R** [comment]
:) :+1:
