### ISSUE TITLE
Livereload midleware error

### ISSUE THREAD

**Issue by dpineiden** [Fantomas42/django-livereload#6]
Hello
I'm try to configuring odjango-livereload n a django project but i have some problems (yet) to setup correctly.
In this case, the middleware doesn't detected. Django give me that:

ImportError: Module "django.middleware.LiveReloadScript" does not define a "LiveReloadScript" attribute/class

What i have to do?

Thanks!

**Comment by Fantomas42** [comment]
Hello, the name of the middleware is `'livereload.middleware.LiveReloadScript'` not `'django.middleware.LiveReloadScript'`.

Regards
